name: Deploy to Azure

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip the application files
      run: |
        echo "$FIREBASE_SERVICE_CRED" > firebase_service_cred.json
        zip -r zipfile.zip . -x '.??*'

    - name: Verify zipfile contents
      run: |
        unzip -l zipfile.zip

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_SERVICE_NAME }}
        package: zipfile.zip

    - name: Clean up
      run: |
        rm zipfile.zip
        rm firebase_service_cred.json